config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks

  root 'user_tasks#index'

  get "auth/:provider/callback" => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout

end

app/models/user.rb
class User < ActiveRecord::Base

  # Create user using the JSON response returned from the facebook API
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
    end
  end

  def small_image
    "http://graph.facebook.com/#{self.uid}/picture?type=small"
  end

  def normal_image
    "http://graph.facebook.com/#{self.uid}/picture?type=normal"
  end
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # We can declare a helper method to make it available to the controller and view
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Sign in
  def create
    auth = request.env['omniauth.auth']

    # Go look in our db for a user with that provider and uid. If they don't exist yet, create them.
    user = User.find_by(provider: auth['provider'], uid: auth['uid']) || User.create_with_omniauth(auth)

    # Once we have the user, set the session[:user_id]
    session[:user_id] = user.id

    redirect_to root_url, notice: "Welcome, #{user.name}!"
  end

  # Sign out
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "All signed out. Goodbye!"
  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]
  before_action :set_user_tasks, only: [:index, :create, :update, :destroy]

  # GET /user_tasks
  # GET /user_tasks.json
  def index
  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.new(user_task_params)

    respond_to do |format|
      if @user_task.save
        format.html { redirect_to @user_task, notice: 'User task was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @user_task }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task, notice: 'User task was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'User task was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private

    def set_user_tasks
      @user_tasks = UserTask.order(:due)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Task Me", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <%= render 'layouts/navbar_links' %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <!-- Show photo -->
    <li>
      <%= image_tag current_user.small_image, class: 'img-responsive' %>
    </li>

    <!-- Sign out link -->
    <li>
      <%= link_to fa_icon('sign-out', text: 'Sign Out'), signout_path, id: 'sign_out' %>
    </li>
  <% else %>
    <!-- Sign in link -->
    <li>
      <%= link_to fa_icon('sign-in', text: 'Sign in with Facebook'), '/auth/facebook', id: 'sign_in' %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function(){
  $('#user_task_due').datepicker({
    format: "yyyy-mm-dd",
    autoclose: true,
    todayHighlight: true
  });
});

app/views/user_tasks/_form.html.erb
<%= simple_form_for(@user_task, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, as: :text, placeholder: 'Make groceries.' %>
    <%= f.input :due, as: :string, placeholder: 'Today!' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_tasks/_user_task.html.erb
<div class="well">
  <%# TODO: Why doesn't the JQuery still work after editing a task? %>
  <%= link_to fa_icon('square-o', text: user_task.description), user_task, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'task' %>

  <%= link_to fa_icon('pencil', text: 'Edit'), edit_user_task_path(user_task), remote: true, class: 'btn btn-xs btn-primary' %>

  <span class="pull-right">
    <em>
      <%= user_task.due.try(:stamp, 'Monday, 12/31/16') %>
    </em>
  </span>
</div>

app/views/user_tasks/create.js.erb
// Re-render the list of tasks
$('#tasks').html("<%= j (render @user_tasks) %>");

// Show the new task button
$('#new-button').show();

// Slide the form up and hide it
$('#task-form').slideUp(350);

app/views/user_tasks/destroy.js.erb
// Re-render the list of tasks
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#new-button')
  .hide();

$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Things To Do</h1>

<div class="row">
  <!-- Add Task Area -->
  <div class="col-sm-4">
    <h3>New Task</h3>
    <%= link_to fa_icon('plus', text: 'Add Task'), new_user_task_path, remote: true, class: 'btn btn-block btn-default', id: 'new-button' %>

    <!-- Form to be populated by JQuery -->
    <div id="task-form"></div>
  </div>

  <!-- All Tasks -->
  <div class="col-sm-8">
    <h3>All Tasks</h3>
    <div id="tasks">
      <%= render @user_tasks %>
    </div>
  </div>
</div>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#new-button')
  .hide();

$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
// Re-render the list of tasks
$('#tasks').html("<%= j (render @user_tasks) %>");

// Show the new task button
$('#new-button').show();

// Slide the form up and hide it
$('#task-form').slideUp(350);